version: '3'
services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"  # Ensure this port is open on your firewall
    volumes:
      - ./data:/data
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
    restart: unless-stopped
    user: "1000:1000"  # Run as user with ID 1000

  battery-sim-server:
    build: ./battery-sim/server
    ports:
      - "5001:5001"  # Ensure this port is open on your firewall
    environment:
      - SERVER_ENV_VAR=example_value  # Replace with actual environment variables
    restart: unless-stopped

  battery-sim-client:
    build: ./battery-sim/client
    ports:
      - "5173:5173"  # Ensure this port is open on your firewall
    environment:
      - CLIENT_ENV_VAR=example_value  # Replace with actual environment variables
      - VITE_SERVER_HOST=battery-sim-server  # Docker service name
      - VITE_SERVER_PORT=5001
    restart: unless-stopped
