services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"  # Ensure this port is open on your firewall
    volumes:
      - ./data:/data
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
    restart: unless-stopped
    user: "1000:1000"  # Run as user with ID 1000

  battery-sim-server:
    build: ./battery-sim/server
    ports:
      - "5001:5001"
      - "5002:5002"
    env_file:
      - ./battery-sim/server/.env
    environment:
      - BATTERY_PORT=5001
      - AUTOPILOT_PORT=5002
    restart: unless-stopped

  battery-sim-client:
    build: ./battery-sim/client
    ports:
      - "5173:5173"  # Ensure this port is open on your firewall
    environment:
      - VITE_BATTERY_API_URL=http://localhost:5001
      - VITE_AUTOPILOT_API_URL=http://localhost:5002
    restart: unless-stopped
